name: Github actions

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        python -m pytest --junitxml=result.xml
        continue-on-error: true
 
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: test-results-${{ matrix.os }}-py${{ matrix.python }}
          path: results.xml